global:
    bpw_edges: [2,30,50]
    beam_correct: True

BBCompSep:
    n_iters: 5000
    nwalkers: 128
    likelihood_type: 'h&l'
    save_prefix: 'test'
    cmb_files: ["./test_bbpower_minimal/data/camb_lens_nobb.dat", 
                "./test_bbpower_minimal/data/camb_lens_r1.dat"]
    fg_model:
        component_1:
            name: Dust
            sed: Dust
            parameters:
                beta_d:
                temp: 19.6
                nu0: 353.
            spectrum:
                alpha_d:
            cross: 
                name: component_2
                param: epsilon
            priors: 
                beta_d: ['Gaussian', [1.59, 0.11]]
                alpha_d: ['tophat', [-1., -0.5, 0.]]
                amp_d: ['tophat', [0., 1., "inf"]]
                epsilon: ['tophat', [-1., -0.1, 1.]]

        component_2:
            name: Synchrotron
            sed: Synchrotron
            parameters:
                beta_pl:
                nu0: 23.
            spectrum:
                alpha_pl:
            priors: 
                beta_pl: ['Gaussian', [-3.1, 0.3]]
                alpha_pl: ['tophat', [-1., -0.5, 0.]]
                amp_pl: ['tophat', [0., 1., "inf"]]
    
