global:
    bpw_edges: [2,30,50]
    beam_correct: True

BBCompSep:
    n_iter: 1000
    cmb_files: ["./test_bbpower_minimal/camb_lens_nobb.dat", 
                "./test_bbpower_minimal/camb_lens_r1.dat"]
    fg_model:
        component_1:
            name: Dust
            sed: Dust
            parameters:
                beta_d:
                temp: 19.6
                nu0: 353.
            spectrum:
                alpha_d:
            cross: 
                name: component_2
                param: epsilon
            priors: 
                beta_d: [1., 1.6, 2.]
                alpha_d: [0, 0.5, 1]
                amp_d: [0, 1, 10000]
                epsilon: [-1., 0, 1.]

        component_2:
            name: Synchrotron
            sed: Synchrotron
            parameters:
                beta_pl:
                nu0: 30.
            spectrum:
                alpha_pl:
            priors: 
                beta_pl: [-4., -3., -2.]
                alpha_pl: [0, 0.5, 1]
                amp_pl: [0, 1, 10000]
    
