global:
    bpw_edges: [2,30,50]
    beam_correct: True

BBCompSep:
    n_iter: 32
    cmb_files: ["/home/max/projects/BBPipe/bbpower/data/camb_lens_nobb.dat", 
                "/home/max/projects/BBPipe/bbpower/data/camb_lens_r1.dat"]
    fg_model:
        component_1:
            name: Dust
            sed: Dust
            parameters:
                beta_d: None
                temp_d: 19.6
                nu_0: 353.
            priors: 
                beta_d: [1., 1.6, 2.]

        component_2:
            name: Synchrotron
            sed: Synchrotron
            parameters:
                beta_pl: None
                nu_0: 30.
            priors: 
                beta_pl: [-4., -3., -2.]
    
