global:
    bpw_edges: [2,30,50]
    beam_correct: True

BBCompSep:
    n_iters: 5000
    nwalkers: 128
    likelihood_type: 'h&l'
    sampler: 'emcee'
    save_prefix: './out_bp0_ph0_an0_EB/test'
    pol_channels: ['E','B']
    l_min: 30
    l_max: 500

    cmb_model:
        cmb_templates: ["/global/cscratch1/sd/damonge/SO/BBPipe_data/bbpower_minimal/camb_lens_nobb.dat", 
                        "/global/cscratch1/sd/damonge/SO/BBPipe_data/bbpower_minimal/camb_lens_r1.dat"]
        params:
            r_tensor: ['r_tensor', 'tophat', [0.00, 0.00, "inf"]]
            A_lens: ['A_lens', 'tophat', [0.00,0.5,2.00]]

    fg_model:
        component_1:
            name: Dust
            sed: Dust
            cl:
                EE: ClPowerLaw
                BB: ClPowerLaw
            sed_parameters:
                beta_d: ['beta_d', 'Gaussian', [1.59, 0.11]]
                temp_d: ['temp', 'fixed', [19.6]]
                nu0_d: ['nu0', 'fixed', [353.]]
            cl_parameters:
                EE:
                   amp_d_ee: ['amp', 'tophat', [0., 10., "inf"]]
                   alpha_d_ee: ['alpha', 'tophat', [-1., -0.42, 0.]]
                   l0_d_ee: ['ell0', 'fixed', [80.]]
                BB:
                   amp_d_bb: ['amp', 'tophat', [0., 5., "inf"]]
                   alpha_d_bb: ['alpha', 'tophat', [-1., -0.42, 0.]]
                   l0_d_bb: ['ell0', 'fixed', [80.]]
            cross: 
                epsilon_ds: ['component_2', 'tophat', [-1., 0., 1.]]

        component_2:
            name: Synchrotron
            sed: Synchrotron
            cl:
                EE: ClPowerLaw
                BB: ClPowerLaw
            sed_parameters:
                beta_s: ['beta_pl', 'Gaussian', [-3.0, 0.3]]
                nu0_s: ['nu0', 'fixed', [23.]]
            cl_parameters:
                EE:
                    amp_s_ee: ['amp', 'tophat', [0., 2., "inf"]]
                    alpha_s_ee: ['alpha', 'tophat', [-1., -0.6, 0.]]
                    l0_s_ee: ['ell0', 'fixed', [80.]]
                BB:
                    amp_s_bb: ['amp', 'tophat', [0., 2., "inf"]]
                    alpha_s_bb: ['alpha', 'tophat', [-1., -0.6, 0.]]
                    l0_s_bb: ['ell0', 'fixed', [80.]]

    systematics:
        bandpasses:
            bandpass_1:
                phase_nu: "/global/homes/d/damonge/SO/pol_angle_hwp/phase_3layer_lf_0.txt"
                parameters:
                    shift_1: ['shift', 'fixed', [0., 0.01]]
                    gain_1: ['gain', 'fixed', [1., 0.01]]
                    angle_1: ['angle', 'fixed', [0., 0.017]]
            bandpass_2:
                phase_nu: "/global/homes/d/damonge/SO/pol_angle_hwp/phase_3layer_lf_0.txt"
                parameters:
                    shift_2: ['shift', 'fixed', [0., 0.01]]
                    gain_2: ['gain', 'fixed', [1., 0.01]]
                    angle_2: ['angle', 'fixed', [0., 0.017]]
            bandpass_3:
                phase_nu: "/global/homes/d/damonge/SO/pol_angle_hwp/phase_3layer_mf_0.txt"
                parameters:
                    shift_3: ['shift', 'fixed', [0., 0.01]]
                    gain_3: ['gain', 'fixed', [1., 0.01]]
                    angle_3: ['angle', 'fixed', [0., 0.017]]
            bandpass_4:
                phase_nu: "/global/homes/d/damonge/SO/pol_angle_hwp/phase_3layer_mf_0.txt"
                parameters:
                    shift_4: ['shift', 'fixed', [0., 0.01]]
                    gain_4: ['gain', 'fixed', [1., 0.01]]
                    angle_4: ['angle', 'fixed', [0., 0.017]]
            bandpass_5:
                phase_nu: "/global/homes/d/damonge/SO/pol_angle_hwp/phase_3layer_uhf_0.txt"
                parameters:
                    shift_5: ['shift', 'fixed', [0., 0.01]]
                    gain_5: ['gain', 'fixed', [1., 0.01]]
                    angle_5: ['angle', 'fixed', [0., 0.017]]
            bandpass_6:
                phase_nu: "/global/homes/d/damonge/SO/pol_angle_hwp/phase_3layer_uhf_0.txt"
                parameters:
                    shift_6: ['shift', 'fixed', [0., 0.01]]
                    gain_6: ['gain', 'fixed', [1., 0.01]]
                    angle_6: ['angle', 'fixed', [0., 0.017]]
